export const appFonts = [
  { id: 'app-inter', name: 'Inter', fontString: '"Inter", sans-serif' },
  { id: 'app-roboto', name: 'Roboto', fontString: '"Roboto", sans-serif' },
  { id: 'app-poppins', name: 'Poppins', fontString: '"Poppins", sans-serif' },
  { id: 'app-nunito', name: 'Nunito', fontString: '"Nunito", sans-serif' },
  { id: 'app-ubuntu', name: 'Ubuntu', fontString: '"Ubuntu", sans-serif' },
  { id: 'app-playfair', name: 'Playfair', fontString: '"Playfair Display", serif' },
  { id: 'app-oswald', name: 'Oswald', fontString: '"Oswald", sans-serif' },
  { id: 'app-roboto-mono', name: 'Roboto Mono', fontString: '"Roboto Mono", monospace' },
  { id: 'app-comic-neue', name: 'Comic Neue', fontString: '"Comic Neue", cursive' },
  { id: 'app-pacifico', name: 'Pacifico', fontString: '"Pacifico", cursive' },
  { id: 'app-bangers', name: 'Bangers', fontString: '"Bangers", cursive' },
  { id: 'app-press-start', name: 'Start', fontString: '"Press Start 2P", cursive' },
  { id: 'app-bungee', name: 'Bungee', fontString: '"Bungee", cursive' },
  { id: 'app-righteous', name: 'Righteous', fontString: '"Righteous", cursive' },
  { id: 'app-monoton', name: 'Monoton', fontString: '"Monoton", cursive' },
  { id: 'app-lobster', name: 'Lobster', fontString: '"Lobster", cursive' },
  { id: 'app-creepster', name: 'Creepster', fontString: '"Creepster", cursive' },
  { id: 'app-luckiest-guy', name: 'Luckiest Guy', fontString: '"Luckiest Guy", cursive' },
  { id: 'app-jetbrains', name: 'JetBrains', fontString: '"JetBrains Mono", monospace' },
  { id: 'app-system', name: 'System Default', fontString: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' },
];
